### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by WolfPackRoxy** [SamB440/Tale-of-Kingdoms#128]
### Summary

Every time i try joining a world i made i keep getting "invalid player data"

### Steps to reproduce

i dont understand what this means

### Expected behaviour

be able to actually join a world and play on it

### Mod list

ColoredGlow Lib
Fabric API
GeckoLib
More Axolotl Variants Mod
BCLib
Bedrock Plus
Better Beacon Placement (Fabric)
BetterEnd
BetterNether
Bookshelf
Hopper+ (Better Hoppers)
HorseInBoat
Icarus
Inmis
Inventory HUD+
JamLib
Lava Clear View (Fabric)
Trinkets (Fabric)
Universal Enchants [Fabric]
Visual Workbench [Fabric]
Waystones (Fabric Edition)
WI Zoom
WMITAF
XP From Crops (Fabric)

**Comment by SamB440** [comment]
Please provide your latest.log after encountering the issue from your .minecraft/logs folder.

**Comment by WolfPackRoxy** [comment]
[latest.log](https://github.com/SamB440/Tale-of-Kingdoms/files/8855861/latest.log)

**Comment by SamB440** [comment]
Tale of Kingdoms doesn't seem to be being used in that log.

**Comment by WolfPackRoxy** [comment]
i dragged the mod(s) directly into the mods folder from winrar
![20220610_140854](https://user-images.githubusercontent.com/73144981/173117427-30c69a3f-d109-425f-acf5-169ebb6930d2.jpg)
![20220610_140907](https://user-images.githubusercontent.com/73144981/173117435-ea72606a-3b04-40c6-a8e9-e7339cbb2954.jpg)
i have no idea why its not showing up in the mod list

**Comment by SamB440** [comment]
I don't know what modid is or where that came from.
Also, don't add the sources jar. You are also using tale of kingdoms 1.0.0 in that list, I believe you need 1.0.2. Can you try the latest 1.19 build? https://github.com/SamB440/Tale-of-Kingdoms/suites/6968838531/artifacts/272237416

**Comment by WolfPackRoxy** [comment]
this is what happens when i try using the 1.19 version(i used fabric And had the latest version!) ![Screenshot 2022-06-18 184856](https://user-images.githubusercontent.com/73144981/174458022-ca223777-cc69-4f78-9d78-fb5c7966e232.png)

**Comment by WolfPackRoxy** [comment]
it lets me join a world now with the 1.18 version, but mc doesnt seem to acknowledge it as if its not in the mod list(when it is)
