### ISSUE TITLE
lone villager bug 

### ISSUE THREAD

**Issue by epicwarrior229** [SamB440/Tale-of-Kingdoms#144]
### Summary

a bug with rescuing lost villagers

### Steps to reproduce

just exit your world and renter it then go up to the lone villager inside the guild and right click him he will give u worthiness for not bringing back any villagers or if u save a villager if u renter your world and go to one of the bedroom inside the guild and find the lost villager u saved if u right click them after u restarted your world it will restart the quest which should not happen 

### Expected behaviour

having to rescue them and not be given free worthiness and restarting world should not restart the quest with it 

### Mod list

im not running anything else 

### Possible fixes

not sure

### Other

no

**Comment by JordanPlayz158** [comment]
Sounds like a persistence problem, the quest is only saved in ram, not in the world file if I had to guess
