### ISSUE TITLE
Crashing on multiplayer when talking to guild master

### ISSUE THREAD

**Issue by kevinjrliang** [SamB440/Tale-of-Kingdoms#153]
### Summary

When starting a server on  LAN, the second player would crash when they talk to the guild master and various other characters. Some characters such as the guards would not crash.

### Steps to reproduce

1. Start a LAN server.
2. Have another player join
3. Have the second player talk to the guild master

### Expected behaviour

The second player should have the same behaviour as the host

### Mod list

ToK, Iris and Sodium.

### Possible fixes

Not sure

### Other

Some characters such as the farmer that gives bread would not cause the second player to crash, but the second player can not talk to them for some reason.

**Comment by SamB440** [comment]
LAN is unsupported, you need to run a dedicated server.
