### ISSUE TITLE
Game crashes on start all versions.

### ISSUE THREAD

**Issue by DJMcBirde** [SamB440/Tale-of-Kingdoms#157]
### Summary

Game crashes on start all versions.

### Steps to reproduce

Download and press play with no other mods.

### Expected behaviour

Menu

### Mod list

ToK
OwOlib
Which is required

### Possible fixes

Unknown

### Relevent logs and/or screenshots/videos

https://pastebin.com/NBrwdBeW

Exit Code -1

### Other

GPU: RTX 4070
CPU: AMD Ryzen 9 5900X
Ram: 32G
M.2 Drive

**Comment by cjtd10** [comment]
its also happening for me i think everyone is having this problem.

**Comment by Poopooracoocoo** [comment]
From the [Discord server](https://discord.gg/fh62mxU):

> ### Tale of Kingdoms is crashing!?
> Fabric made changes in version 0.15 of their loader which led to many mods crashing.
>
> You must use Fabric Loader 0.14.25.
This also means you must use this Fabric API version: https://modrinth.com/mod/fabric-api/version/0.90.7+1.20.1
>
> There is no ETA for the next Tale of Kingdoms update.

**Comment by DJMcBirde** [comment]
Ok. Since it wasn't clarified by the mods before closing the case. Only 1.20.1 and below works. Thanks. Your welcome.
