### ISSUE TITLE
Selling items results in double the amount of coins as the sell value.

### ISSUE THREAD

**Issue by SamB440** [SamB440/Tale-of-Kingdoms#59]
In GitLab by @jordanplayz158 on Jun 5, 2021, 17:21

## Summary
When you go to sell an item, you put the item in the sell slot and then you are given 2x the sell value it is worth (client and server calling the method)

## Steps to reproduce
1. Get a sellable item
2. Go to any merchant (blacksmith was used in the video)
3. Go to the sell gui (click on the sell button)
4. Sell the item

## What is the current bug behaviour?
When you sell an item, you get 2x the sell value

## What is the expected behaviour?
When you sell an item, you should get 1x the sell value.

## Relevant logs and/or screenshots/videos
https://discord.com/channels/282242806695591938/844674162438045736/850769330769362976
OR
https://streamable.com/bmcik7

## Possible fixes
Will look through code and update issue accordingly.

**Comment by JordanPlayz158** [comment]
This was assigned to me but it appears that Sam fixed this issue in both master and tier one so this can now be closed.

**Comment by JordanPlayz158** [comment]
Found the commit, 05a1c6d6843646ea9b25500ecc71550349633aa9
